orbs:
  heroku: circleci/heroku@0.0.8
  node: circleci/node@1.1
version: 2.1
workflows:
  version: 2
  heroku_deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
      - deploy-staging:
          requires:
            - build
      - deploy-production:
          requires:
            - build
jobs:
  build:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: 14.16.0
          npm-version: 7.5.3
          install-yarn: false
      - node/with-cache:
          steps:
            - run: npm install
            
  deploy-dev:
    executor: heroku/default
    steps:
      - checkout
      - run: git-crypt unlock
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: dev
          app-name: wertgarantie-demo-shop-dev
  deploy-staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: staging
          app-name: wertgarantie-demo-shop-staging
  deploy-production:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
          app-name: wertgarantie-demo-shop-prod
