orbs:
  heroku: circleci/heroku@0.0.8
version: 2.1
workflows:
  version: 2
  heroku_deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
      - deploy-staging:
          requires:
            - build
      - deploy-production:
          requires:
            - build
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy-dev:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: development
          app-name: wertgarantie-demo-shop-dev
  deploy-staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: staging
          app-name: wertgarantie-demo-shop-staging
  deploy-production:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
          app-name: wertgarantie-demo-shop-prod
